import { Hono } from "hono";
import { createClient } from "@blinkdotnew/sdk";

const previewApp = new Hono<{ Bindings: Record<string, string> }>();

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const BASE_STYLE = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; margin: 0; color: #1e293b; background: #f8fafc; line-height: 1.65; }
  .footer { text-align: center; padding: 24px 20px; color: #94a3b8; font-size: 12px; }
`;

function wrapPage(title: string, bodyHtml: string, extraStyle = ""): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${escapeHtml(title)}</title>
<style>${BASE_STYLE}${extraStyle}</style>
</head>
<body>
${bodyHtml}
<div class="footer">Generated by AgentOrch</div>
</body>
</html>`;
}

interface AuditReportData {
  headline: string;
  overallImpression: string;
  criticalIssues: string[];
  quickWins: string[];
  closingPitch: string;
}

function isAuditData(v: any): v is AuditReportData {
  return v && typeof v === "object" && Array.isArray(v.criticalIssues) && Array.isArray(v.quickWins);
}

function renderAuditReport(companyName: string, data: AuditReportData): string {
  const issuesHtml = data.criticalIssues.length
    ? data.criticalIssues.map((issue) => `<li class="issue"><span class="issue-icon">!</span><span>${escapeHtml(issue)}</span></li>`).join("")
    : `<li class="issue muted">Full issue breakdown pending — check back shortly.</li>`;
  const winsHtml = data.quickWins.length
    ? data.quickWins.map((win) => `<li class="win"><span class="win-icon">✓</span><span>${escapeHtml(win)}</span></li>`).join("")
    : `<li class="win muted">Quick-win recommendations pending.</li>`;

  return wrapPage(
    `SEO Audit — ${companyName}`,
    `<div class="wrap">
      <div class="eyebrow">SEO &amp; AEO Audit Report</div>
      <h1>${escapeHtml(data.headline)}</h1>
      <p class="company">Prepared for <strong>${escapeHtml(companyName)}</strong></p>
      <div class="card">
        <h2>Current Standing</h2>
        <p>${escapeHtml(data.overallImpression)}</p>
      </div>
      <div class="card">
        <h2>Critical Issues Found</h2>
        <ul class="list">${issuesHtml}</ul>
      </div>
      <div class="card">
        <h2>Quick Wins (30 days)</h2>
        <ul class="list">${winsHtml}</ul>
      </div>
      <div class="closing">
        <p>${escapeHtml(data.closingPitch)}</p>
        <div class="cta-banner">Reply to the email that sent you this report to get started.</div>
      </div>
    </div>`,
    `
    .wrap { max-width: 760px; margin: 0 auto; padding: 56px 24px 24px; }
    .eyebrow { color: #0D9488; font-weight: 700; font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase; margin-bottom: 10px; }
    h1 { font-size: 32px; line-height: 1.25; margin: 0 0 8px; color: #0f172a; }
    .company { color: #64748b; margin: 0 0 32px; font-size: 14px; }
    .card { background: #fff; border: 1px solid #e2e8f0; border-radius: 14px; padding: 24px 28px; margin-bottom: 20px; box-shadow: 0 1px 2px rgba(15,23,42,0.04); }
    .card h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 0.06em; color: #334155; margin: 0 0 14px; }
    .list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 12px; }
    .issue, .win { display: flex; align-items: flex-start; gap: 12px; font-size: 15px; }
    .issue-icon, .win-icon { flex-shrink: 0; width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700; }
    .issue-icon { background: #fef2f2; color: #dc2626; }
    .win-icon { background: #f0fdfa; color: #0D9488; }
    .muted { color: #94a3b8; font-style: italic; }
    .closing { text-align: center; padding: 32px 0 8px; }
    .closing p { font-size: 16px; color: #334155; max-width: 560px; margin: 0 auto 20px; }
    .cta-banner { display: inline-block; background: #0D9488; color: #fff; font-weight: 700; padding: 14px 32px; border-radius: 999px; font-size: 15px; }
    `
  );
}

interface WebsitePreviewData {
  heroHeadline: string;
  heroSubheadline: string;
  pillars: { title: string; description: string }[];
  cta: string;
}

function isWebsiteData(v: any): v is WebsitePreviewData {
  return v && typeof v === "object" && Array.isArray(v.pillars);
}

function renderWebsitePreview(companyName: string, data: WebsitePreviewData, phone?: string): string {
  const pillarsHtml = data.pillars.length
    ? data.pillars.map((p) => `<div class="pillar"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.description)}</p></div>`).join("")
    : `<div class="pillar muted"><p>Service details coming soon.</p></div>`;
  const ctaTag = phone
    ? `<a class="cta" href="tel:${escapeHtml(phone)}">${escapeHtml(data.cta)}</a>`
    : `<div class="cta">${escapeHtml(data.cta)}</div>`;

  return wrapPage(
    `${companyName} — Website Preview`,
    `<div class="hero">
      <div class="hero-inner">
        <div class="badge">${escapeHtml(companyName)}</div>
        <h1>${escapeHtml(data.heroHeadline)}</h1>
        <p>${escapeHtml(data.heroSubheadline)}</p>
        ${ctaTag}
      </div>
    </div>
    <div class="pillars">${pillarsHtml}</div>
    <div class="preview-note">This is a preview build — the full site includes your real photos, reviews, and booking flow.</div>`,
    `
    .hero { background: linear-gradient(135deg, #0f172a 0%, #0D9488 140%); color: #fff; padding: 80px 24px; text-align: center; }
    .hero-inner { max-width: 640px; margin: 0 auto; }
    .badge { display: inline-block; background: rgba(255,255,255,0.12); padding: 6px 16px; border-radius: 999px; font-size: 12px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; margin-bottom: 20px; }
    .hero h1 { font-size: 38px; line-height: 1.2; margin: 0 0 16px; }
    .hero p { font-size: 17px; color: rgba(255,255,255,0.85); max-width: 480px; margin: 0 auto 32px; }
    .cta, a.cta { display: inline-block; background: #fff; color: #0D9488; font-weight: 700; padding: 14px 36px; border-radius: 999px; font-size: 15px; text-decoration: none; }
    .pillars { max-width: 900px; margin: -36px auto 0; padding: 0 24px 48px; display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; position: relative; }
    .pillar { background: #fff; border: 1px solid #e2e8f0; border-radius: 14px; padding: 24px; box-shadow: 0 8px 24px rgba(15,23,42,0.06); }
    .pillar h3 { margin: 0 0 8px; font-size: 16px; color: #0f172a; }
    .pillar p { margin: 0; font-size: 14px; color: #64748b; }
    .pillar.muted p { font-style: italic; color: #94a3b8; }
    .preview-note { text-align: center; font-size: 13px; color: #94a3b8; padding: 0 24px 40px; }
    `
  );
}

function renderLegacyText(title: string, content: string): string {
  return wrapPage(
    title,
    `<div class="wrap"><h1>${escapeHtml(title)}</h1><pre>${escapeHtml(content)}</pre></div>`,
    `.wrap { max-width: 720px; margin: 0 auto; padding: 56px 24px 24px; } h1 { color: #0D9488; } pre { white-space: pre-wrap; font-family: inherit; background: #fff; border: 1px solid #e2e8f0; border-radius: 14px; padding: 24px; }`
  );
}

previewApp.get("/audit/:leadId", async (c) => {
  const env = c.env as Record<string, string>;
  const blink = createClient({ projectId: env.BLINK_PROJECT_ID, secretKey: env.BLINK_SECRET_KEY });
  const leadId = c.req.param("leadId");
  const leads = (await blink.db.leads.list({ where: { id: leadId }, limit: 1 })) as any[];
  const lead = leads[0];
  const assets = (await blink.db.generatedAssets.list({ where: { leadId, type: "audit_report" }, limit: 1 })) as any[];
  const asset = assets[0];
  if (!asset) return c.text("Audit report not found for this lead.", 404);
  const companyName = lead?.companyName || "Report";

  let parsed: any = null;
  try { parsed = JSON.parse(asset.content || ""); } catch { /* legacy plain-text asset */ }

  const html = isAuditData(parsed)
    ? renderAuditReport(companyName, parsed)
    : renderLegacyText(`SEO Audit — ${companyName}`, asset.content || "");
  return c.html(html);
});

previewApp.get("/site/:leadId", async (c) => {
  const env = c.env as Record<string, string>;
  const blink = createClient({ projectId: env.BLINK_PROJECT_ID, secretKey: env.BLINK_SECRET_KEY });
  const leadId = c.req.param("leadId");
  const leads = (await blink.db.leads.list({ where: { id: leadId }, limit: 1 })) as any[];
  const lead = leads[0];
  const assets = (await blink.db.generatedAssets.list({ where: { leadId, type: "custom_website" }, limit: 1 })) as any[];
  const asset = assets[0];
  if (!asset) return c.text("Website preview not found for this lead.", 404);
  const companyName = lead?.companyName || "Preview";

  let parsed: any = null;
  try { parsed = JSON.parse(asset.content || ""); } catch { /* legacy plain-text asset */ }

  const html = isWebsiteData(parsed)
    ? renderWebsitePreview(companyName, parsed, lead?.phone)
    : renderLegacyText(`${companyName} — Website Preview`, asset.content || "");
  return c.html(html);
});

export default previewApp;
