import { Hono } from "hono";
import { createClient } from "@blinkdotnew/sdk";

const previewApp = new Hono<{ Bindings: Record<string, string> }>();

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function renderPage(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: -apple-system, Arial, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 20px; color: #1e293b; line-height: 1.7; }
  h1 { color: #0D9488; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 13px; }
  pre { white-space: pre-wrap; font-family: inherit; }
</style>
</head>
<body>
${bodyHtml}
<div class="footer">Generated by AgentOrch</div>
</body>
</html>`;
}

previewApp.get("/audit/:leadId", async (c) => {
  const env = c.env as Record<string, string>;
  const blink = createClient({ projectId: env.BLINK_PROJECT_ID, secretKey: env.BLINK_SECRET_KEY });
  const leadId = c.req.param("leadId");
  const leads = (await blink.db.leads.list({ where: { id: leadId }, limit: 1 })) as any[];
  const lead = leads[0];
  const assets = (await blink.db.generatedAssets.list({ where: { leadId, type: "audit_report" }, limit: 1 })) as any[];
  const asset = assets[0];
  if (!asset) return c.text("Audit report not found for this lead.", 404);
  const html = renderPage(
    `SEO Audit — ${lead?.companyName || "Report"}`,
    `<h1>SEO Audit Report${lead ? `: ${escapeHtml(lead.companyName)}` : ""}</h1><pre>${escapeHtml(asset.content || "")}</pre>`
  );
  return c.html(html);
});

previewApp.get("/site/:leadId", async (c) => {
  const env = c.env as Record<string, string>;
  const blink = createClient({ projectId: env.BLINK_PROJECT_ID, secretKey: env.BLINK_SECRET_KEY });
  const leadId = c.req.param("leadId");
  const leads = (await blink.db.leads.list({ where: { id: leadId }, limit: 1 })) as any[];
  const lead = leads[0];
  const assets = (await blink.db.generatedAssets.list({ where: { leadId, type: "custom_website" }, limit: 1 })) as any[];
  const asset = assets[0];
  if (!asset) return c.text("Website preview not found for this lead.", 404);
  const html = renderPage(
    `${lead?.companyName || "Preview"} — Website Preview`,
    `<h1>${escapeHtml(lead?.companyName || "Preview")}</h1><pre>${escapeHtml(asset.content || "")}</pre>`
  );
  return c.html(html);
});

export default previewApp;
